# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock    # run hyprlock if not already running
    before_sleep_cmd = hyprlock
    after_sleep_cmd = wlopm --on \*
}

# Dim screen after 3 minutes
listener {
    timeout = 180
    on-timeout = brightnessctl set 20%
    on-resume = brightnessctl set 100%
}

# Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Turn off monitors after 10 minutes
listener {
    timeout = 600
    on-timeout = wlopm --off \*
    on-resume = wlopm --on \*
}

# Suspend system after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
