# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || (playerctl -a pause; hyprlock)    # pause media, then lock
    before_sleep_cmd = playerctl -a pause; hyprlock
    after_sleep_cmd = sleep 1; wlopm --on \*; 
}

# Dim screen after 3 minutes
listener {
    timeout = 180
    on-timeout = brightnessctl set 20%
    on-resume = brightnessctl set 100%
}

# Lock screen after 10 minutes
listener {
    timeout = 600
    on-timeout = playerctl -a pause; hyprlock
}

# Turn off monitors after 15 minutes
listener {
    timeout = 900
    on-timeout = wlopm --off \*
    on-resume = sleep 1; wlopm --on \*
}

# Suspend system after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
