# name: White Black Green

# The basic colors
foreground              #0a0a0a
background              #e8e8e8
selection_foreground    #e8e8e8
selection_background    #60DD2A

# Cursor colors
cursor                  #60DD2A
cursor_text_color       #e8e8e8

# URL underline color when hovering with mouse
url_color               #3aaa10

# Kitty window border colors
active_border_color     #60DD2A
inactive_border_color   #cccccc
bell_border_color       #0a0a0a

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #e8e8e8
active_tab_background   #60DD2A
inactive_tab_foreground #555555
inactive_tab_background #dddddd
tab_bar_background      #e8e8e8

# Colors for marks (marked text in the terminal)
mark1_foreground        #e8e8e8
mark1_background        #60DD2A
mark2_foreground        #e8e8e8
mark2_background        #0a0a0a
mark3_foreground        #e8e8e8
mark3_background        #888888

# The 16 terminal colors

# black
color0  #0a0a0a
color8  #555555

# red
color1  #cc3333
color9  #cc3333

# green
color2  #3aaa10
color10 #60DD2A

# yellow
color3  #0a0a0a
color11 #333333

# blue
color4  #555555
color12 #333333

# magenta
color5  #444444
color13 #0a0a0a

# cyan
color6  #3aaa10
color14 #60DD2A

# white
color7  #e8e8e8
color15 #e8e8e8